services:
  api_bun:
    build: api_bun/.
    volumes:
      - $PWD/api_bun/:/usr/src/app
    container_name: api_bun
    hostname: api_bun
    restart: always
    networks: 
      - metanet1-load
    environment:
      BUN_PORT: 3000
      POSTGRES_CONN_STRING: postgresql://metabase:mysecretpassword@postgres-app-db-load:5432/metabase
      CREATE_METRICS_TABLE: true
      VERSION: 1.50.0-RC2
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 128M
        reservations:
          cpus: '1'
          memory: 64M
    depends_on:
      postgres-app-db-load:
        condition: service_healthy
  metabase-load:
    image: metabase/metabase-enterprise:v1.50.0-RC2
    container_name: metabase-load
    hostname: metabase
    volumes: 
      - /dev/urandom:/dev/random:ro
      - $PWD/logging_config:/metabase.db
    ports:
      - 3000:3000
    environment: 
      MB_DB_TYPE: postgres
      MB_DB_HOST: postgres-app-db-load
      MB_DB_PORT: 5432
      MB_DB_DBNAME: metabase
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      # MB_DB_CONNECTION_URI: "postgres://postgres-app-db-load:5432/metabase?user=metabase&password=mysecretpassword"
      MB_SITE_URL: http://localhost:3001/
      MB_APPLICATION_DB_MAX_CONNECTION_POOL_SIZE: 500 # This number is super high in order to make the App DB not throttle Metabase
      MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE: FALSE
      MB_DISABLE_SESSION_THROTTLE: true
      JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true -Xms1500m -Xmx3500m -Dlog4j.configurationFile=file:/metabase.db/log4j2.xml
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '2'
          memory: 2048M
    networks: 
      - metanet1-load
    depends_on: 
      postgres-app-db-load:
        condition: service_healthy
      postgres-data1-load:
        condition: service_healthy
    healthcheck:
      test: curl --fail -X GET -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 10
  postgres-app-db-load:
    image: postgres:16.2-alpine
    container_name: postgres-app-db-load
    hostname: postgres-app-db-load
    environment:
      - "POSTGRES_USER=metabase"
      - "POSTGRES_DB=metabase"
      - "POSTGRES_PASSWORD=mysecretpassword"
    ports:
      - 5432:5432
    volumes:
      - $PWD/postgres_origin:/var/lib/postgresql/data
    networks:
      - metanet1-load
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '1'
          memory: 2048M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d metabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: -c 'max_connections=10000'
  setup-load:
    build: setup/.
    container_name: setup-load
    volumes:
      - $PWD/setup/setup.py:/app/setup.py
    networks:
      - metanet1-load
    depends_on:
      metabase-load:
        condition: service_healthy
    command: python /app/setup.py
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 64M
        reservations:
          cpus: '0.5'
          memory: 32M
    environment:
      host: http://metabase
      port: 3000
      dbs: 1
  postgres-data1-load:
    image:  metabase/qa-databases:postgres-sample-15
    container_name: postgres-data1-load
    hostname: postgres-data1-load
    networks: 
      - metanet1-load
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d sample"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: -c 'max_connections=10000'
  k6-load:
    image: grafana/k6:0.51.0
    volumes:
      - $PWD/k6-script/script.js:/home/k6/script.js
    networks:
      - metanet1-load
    environment:
      host: http://metabase:3000
      user: a@b.com
      password: metabot1
    depends_on:
      setup-load:
        condition: service_completed_successfully
    command: run /home/k6/script.js
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M

networks: 
  metanet1-load:
    driver: bridge
